# Generated by Django 4.2.13 on 2024-06-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForneceJuntos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, null=True),
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='id',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='CEP',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='agencia',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='banco',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='conta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
