# Generated by Django 4.2.13 on 2024-06-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForneceJuntos', '0002_remove_fornecedor_id_fornecedor_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(default='00000000000000', max_length=18, primary_key=True, serialize=False),
        ),
    ]
