# Generated by Django 4.2.13 on 2024-06-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForneceJuntos', '0003_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, primary_key=True, serialize=False),
        ),
    ]
