# Generated by Django 4.2.13 on 2024-06-04 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForneceJuntos', '0004_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Telefone'), (2, 'Celular'), (3, 'Email')])),
                ('contato', models.CharField(max_length=100)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='ForneceJuntos.fornecedor')),
            ],
        ),
    ]
