# Generated by Django 4.2.13 on 2024-06-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForneceJuntos', '0005_contato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
