# Generated by Django 4.2.13 on 2024-06-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForneceJuntos', '0008_alter_contato_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='ativo',
        ),
    ]
