# Generated by Django 4.2.13 on 2024-06-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForneceJuntos', '0009_remove_contato_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='tipo_bebida',
            field=models.CharField(choices=[('Destilados', 'Destilados'), ('Vinhos', 'Vinhos'), ('Cervejas', 'Cervejas'), ('Espumantes', 'Espumantes'), ('Licores', 'Licores'), ('Refrescos', 'Refrescos'), ('Água', 'Água')], default='Destilados', max_length=20),
        ),
    ]
